### Data analysis

* Data :data is facts and statistics collected together for reference or analysis
* Data analysis:
    * is a process of obtaining raw data and subsequently converting it into information,useful for decision making
    * is a technique to collect , transform and organize data to make future predictions
    * all sorts of data analysis,Analyzing the numerical data with numpy,tabular data with pandas 
    and visualization by matplotlib and exploratory data analysis

### Data Collection

* Primary data: 
    * refers to first hand data generated by the research himself/herself
    * real time data
    * Surveys, Observations,experiments,questionanaire,personal interviews etc
    * Expensive and takes long time
    
* Secondary data:
    * data which is collected by someone else earlier
    * Past data
    * Websites, books, journals,articles, internal records, government publications etc
    * Economical and takes short time

### Types of data

* Structured data: row/columns -> tabular format -> excel file,.csv,.tsv etc
* Unstructured data: pictures,videos,text,.ppt,.pdf,log files ,voices
* Semi structured data: xml,json,html files {key:value}

### Data types in statistics

* Numerical data: data in the form of numbers
    *1.Discrete data: 
        * is a count that involves only integers. can't be subdivided into parts
        * ex: no of students in a class
        * no of workers in a company etc
        
    *2.Continuous data:
        * Continuous data could be meaniningfully divided into finger levels
        * It can be measured on a scale & have a numerical value
        * ex: height,weight of a children etc..
        
* Categorical data: made of words
* 1.Nominal data
                * nominal data is used for labelling variables
                * Ex: Gender(male,female)
* 2.Ordinal data
                * Ordinal data is data which is placed into some kind of order by their position on a scale
                * Ex: 1st ,2nd,3rd persons in a competition





### Numpy  - Numerical python
* It is a open source python library
* It is used for scientific computing and working with arrays
* Numpy provides high level functioning tools to works with arrays
* Using numpy we can perform both logical and mathematical operations on arrays
* It also has functions in domain of Linear algebra,fourier transforms and matrices

In [2]:
l=[10,20,340,89]

# 100
l+100

TypeError: can only concatenate list (not "int") to list

## Advantages of numpy over list

* Consumes less memory'
* fast when compared with the list
* convinient to use

In [3]:
import numpy as np

In [4]:
# Creating an array

l=[10,20,30,40,50]
a=np.array(l)
a

array([10, 20, 30, 40, 50])

In [5]:
print(a)
print(type(a))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [6]:
b=a+100
b

array([110, 120, 130, 140, 150])

In [14]:
print(a.ndim)  # no of dimensions
print(a.size)  # size of the array
print(a.itemsize)  # itemsize of each elements
print(a.max())
print(a.min())

1
5
4
50
10


In [15]:
a1=np.array([10,20,30,40,50],dtype="complex")
a1

array([10.+0.j, 20.+0.j, 30.+0.j, 40.+0.j, 50.+0.j])

In [17]:
a2=np.array([11,12,13],ndmin=2)
print(a2)
print(a2.ndim)

[[11 12 13]]
2


In [18]:
b=np.array([10,85,45,79,215])
b

array([ 10,  85,  45,  79, 215])

In [23]:
print(b.sum())
print(b.max())
print(b.min())
print(b.argmax())   # index of max value
print(b.argmin())

434
215
10
4
0


In [25]:
# range() and arange()

for i in range(1,11):
    print(i,end=" ")

1 2 3 4 5 6 7 8 9 10 

In [26]:
a=np.array(range(1,101))
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [27]:
# create an array with even numbers in the range of 100

even=np.array(range(2,101,2))
even

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [28]:
# array with odd numbers in the range of 100 to 200

In [29]:
# arange() -> belongs to numpy

a=np.arange(1,101)
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [33]:
a=np.arange(25)
print(a)
print(a.ndim)

# converting 1D into 2D array

b=a.reshape(5,5)
print(b)
print(b.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
1
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
2


In [34]:
a=np.arange(24)
b=a.reshape(6,4)
print(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


* linspace() -> returns no of spaces evenly w.r.to given interval

In [35]:
a=np.linspace(1,20,5)
a

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

In [36]:
b=np.linspace(1,5)
b

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

### Array initialization

* np.ones() -> creates an array with given shape and type with ones

In [38]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [40]:
np.ones([2,2],dtype=int)

array([[1, 1],
       [1, 1]])

In [41]:
np.ones((3,2,1))

array([[[1.],
        [1.]],

       [[1.],
        [1.]],

       [[1.],
        [1.]]])

In [42]:
np.zeros(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [43]:
np.zeros([2,2],dtype=int)

array([[0, 0],
       [0, 0]])

In [44]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [45]:
a=np.full([2,2],60)
a

array([[60, 60],
       [60, 60]])

* eye() -> create an 2D array with 1's on diagonal and 0's elsewhere

In [46]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [47]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [48]:
np.eye(2,dtype=int)

array([[1, 0],
       [0, 1]])

In [49]:
# 3,4,5

np.diag([3,4,5])

array([[3, 0, 0],
       [0, 4, 0],
       [0, 0, 5]])

In [50]:
np.empty(3)

array([1., 1., 1.])

In [51]:
np.empty(9)

array([1., 0., 0., 0., 1., 0., 0., 0., 1.])

In [52]:
np.empty([2,2])

array([[1., 0.],
       [0., 1.]])

In [59]:
# accessing 1D array elements

a=np.array([12,34,55,85])
print(a)
print(a[0])
print(a[1])
print(a[2])
print(a[1]+a[2])
print(a[::-1])
print(a[-1])

[12 34 55 85]
12
34
55
89
[85 55 34 12]
85


In [60]:
a=np.array([90,9.8,'hello'])
a

array(['90', '9.8', 'hello'], dtype='<U32')

In [61]:
# Creating 2 Dimensional array

l1=[10,20,30,40]
l2=[50,60,70,80]
b=np.array([l1,l2])
print(b)
print(b.ndim)

[[10 20 30 40]
 [50 60 70 80]]
2


In [66]:
# Accessing 2D array elements

print(b[0,0])  # row index,col index
print(b[0,1])
print(b[1,0])

# 70

print(b[1,2])

10
20
50
70


In [67]:
# creating 3D array

c=np.array([ [[10,20],[30,40]],
         [[50,60],[70,80]] ])
print(c)
print(c.ndim)

[[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]]
3


In [72]:
# accessing 3D array elements

print(c[0])
print(c[1])

[[10 20]
 [30 40]]
[[50 60]
 [70 80]]


In [75]:
print(c[0,0,0])
print(c[0,0,1])
print(c[1,1,1])

10
20
80


In [76]:
# random()
np.random.random()  # random value b/w 0 to 1

0.6943378424720508

In [77]:
# randint() 

np.random.randint(700)

652

In [81]:
np.random.randint(10,100,5)

array([42, 23, 37, 44, 49])

In [82]:
a=np.random.randint(100,200,10)
a

array([152, 197, 148, 192, 105, 196, 115, 198, 162, 104])

In [83]:
# fancy indexing or boolean indexing

a>150

array([ True,  True, False,  True, False,  True, False,  True,  True,
       False])

In [84]:
a[a>150]

array([152, 197, 192, 196, 198, 162])

In [85]:
# slicing

a=np.random.randint(1,10,5)
a

array([2, 3, 3, 9, 6])

In [87]:
a[1:4]

array([3, 3, 9])

In [88]:
a=np.arange(32)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [89]:
a.reshape(4,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [90]:
a.reshape(8,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [91]:
a.reshape(4,4,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [92]:
a.reshape(-1,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [93]:
a.reshape(8,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [94]:
def grt(a,b):
    if a>b:
        return a
    else:
        return b
    
grt(90,87)

90

In [95]:
grt([10,29,78],[90,65,76])

[90, 65, 76]

In [97]:
vgrt=np.vectorize(grt)
vgrt([10,29,78],[90,65,76])

array([90, 65, 78])

In [99]:
# staking 

a=np.array([1,2,3])
b=np.array([4,5,6])
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [100]:
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [102]:
# mathematical operations

a1=np.arange(1,4)
a2=np.array([4,5,6])
a1

array([1, 2, 3])

In [103]:
a2

array([4, 5, 6])

In [104]:
print(a1+a2)
print(a1-a2)
print(a1*a2)
print(a1/a2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [105]:
print(a1.mean())

2.0


In [108]:
a=np.array([10,50,20,40,30])
print(a.mean())
print(np.mean(a))
print(np.median(a))

30.0
30.0
30.0
